### ISSUE TITLE
New Logo and Favicon

### ISSUE THREAD

**Issue by jubi4dition** [jubi4dition/yourcontacts#2]
Yourcontacts needs a new logo for the navbar and a new favicon! 

Solutions? :)

**Comment by Teva** [comment]
Hello,

Why didn't you use the CodeIgniter-Bootstrap fork (here @ https://github.com/sjlu/CodeIgniter-Bootstrap).

Actually I'm planning to use CodeIgniter + Bootstrap but I still can't define whether the fork is a better suit or not !

Whats your point of view on that matter ?

**Comment by jubi4dition** [comment]
Hello,
you could use this project, there is everything what you need for Codeigniter + Bootstrap. But it's not a big thing to combine them, just copy the files in the assets folder and then include them in the view file.
