### ISSUE TITLE
CSS can't get loaded

### ISSUE THREAD

**Issue by arashm** [jubi4dition/yourcontacts#3]
You've used base_url() without echo in header.php (and other files) so there will be no URL there in the output :)

**Comment by jubi4dition** [comment]
Hallo, there should be a URL in the output :) I am using php short tags (http://codeigniter.com/user_guide/general/alternative_php.html). Is it not working on your system?
But good point, i could active the feature in CI to rewrite the tags on-the-fly for systems which have not active short tags in the PHP ini file.

**Comment by wax83** [comment]
Hello jubi4dition!

I'd like to use your app for educational purposes, (only for meself) namely to get something similar in Rails,
using your work as a base. Hoping its not a huge problem for you!
I've encountered some problems though, for instance in the 'site' controller's index action when the 'contacts' view gets rendered u used an iteration to display the attributes of the conacts table in a tabular fashion.. right? But I got a nasty runtime error saying:

"A PHP Error was encountered
Severity: Notice
Message: Undefined variable: i
Filename: views/contacts.php
Line Number: 22"

..in every table cell!
What the heck?!?
Anyways, all suggestions are greatly appreciated, & please excuse my silllyness I haven't touched php for a while.
